### ISSUE TITLE
Output buffer initialization overhead

### ISSUE THREAD

**Issue by sign60intel** [intel-ai/omniscidb#198]
We have an output buffer initialization overhead. Previously we worked on that problem to disable such initialization but new tests revealed another problem in this area. We might have a case where we initialize 4 bytes per each output row. For series such initialization becomes quite significant – 8-10% of the whole execution time. It should be possible to get rid of this initialization

https://github.com/intel-ai/omniscidb/issues/175

**Comment by sign60intel** [comment]
Supposed script (from @ienkovich) to investigate the problem:
```
import os
import pyarrow

os.environ["http_proxy"] = ""
os.environ["https_proxy"] = ""

import modin.config

modin.config.IsExperimental.put(True)
modin.config.Engine.put("native")
modin.config.StorageFormat.put("omnisci")

import modin.pandas as pd
import pandas

data = {"a": [2] * 300000000}
df = pd.DataFrame(data)
df = df * 5
_ = df.shape
```

**Comment by Garra1980** [comment]
I believe initial case was operations with df's columns, like df[a] + 5

**Comment by ienkovich** [comment]
There is no difference for the initialization problem. But IIRC it was originally a 10 columns vs single column dataframe multiplication by a scalar.

**Comment by Garra1980** [comment]
> There is no difference for the initialization problem.

Ah, ok then, thanks

**Comment by sign60intel** [comment]
https://github.com/intel-ai/omniscidb/pull/199

**Comment by sign60intel** [comment]
the fix was merged
