### ISSUE TITLE
Improve performance of  ArrowResultSetConverter::getArrowTable

### ISSUE THREAD

**Issue by novichkovg** [intel-ai/omniscidb#200]
Related to the issue #175.  Need to improve performance of the function on a single column. 

The plan:
- [x] Build OmniSciDb under Conda
- [x] In this environment, run it and reproduce the problem
- [x] Implement Zero Copy
- [x] Test Zero Copy implementation
- [x] Parallelization within a single column
- [ ] Employ AVX512 vectorization to BITMAP creation

**Comment by novichkovg** [comment]
Confirming the problem, multiplying by 2 a single column of size 100 mln is 6.27 times slower than multiplying by 2  10 columns each of size 10 mln.

```
column size   ms
  100000000  709
   10000000  113
```

**Comment by novichkovg** [comment]
More detailed analysis reveals that speed up for 10 columns depends on the data size.  A probable explanation for that is the overhead of launching additional thread (for each column),
![image](https://user-images.githubusercontent.com/65812474/141981928-bc3efa06-e6d0-4687-8d7a-6831299b0df0.png)

**Comment by Garra1980** [comment]
Not sure I got the point about overhead - 1 column case is slower

cc @ienkovich

**Comment by novichkovg** [comment]
> Not sure I got the point about overhead - 1 column case is slower
> 
> cc @ienkovich
I mean that the speedup is not constant; rather it depends on the data size.  It is more or less constant for the sizes 80, 90, 100 mln, for 10 or 30 mln speedup is modest.

**Comment by Garra1980** [comment]
Ah, I see, thanks

**Comment by novichkovg** [comment]
From discussion with @ienkovich today, it seems like we are dealing with a legacy code here. They have this 
```
std::vector<std::unique_ptr<ResultSetStorage>> appended_storage_
```
and 
```
std::unique_ptr<ResultSetStorage> storage_;
```
And then they use these two variables separately.  Why not to use just the definition below?
```
std::vector<std::unique_ptr<ResultSetStorage>> storage_;
```
"Code reuse? Never heard of it", it seems.

**Comment by novichkovg** [comment]
Added to ```class ResultSet```:
 - [x] ```bool ResultSet::isChunkedZeroCopyColumnarConversionPossible(size_t column_idx) const; ```
 - [x] ```std::vector<std::pair<const int8_t*, size_t>> ResultSet::getChunkedColumnarBuffer(size_t column_idx);```

Added to ```class ResultSetStorage```:
 - [x] ```size_t ResultSetStorage::getColOffInBytes(size_t column_idx) const;```
 
Added to ```ArrowResultSetConverter.cpp```:
```
template <typename C_TYPE,
          typename ARROW_TYPE = typename arrow::CTypeTraits<C_TYPE>::ArrowType>
void convert_column(ResultSetPtr result,
                    size_t col,
                    size_t entry_count,
                    std::shared_ptr<arrow::ChunkedArray>& out)
```
TODO (step1): complete implementation of ```convert_column()```.

**Comment by Garra1980** [comment]
Just in case - please do not mix different changes in one PR. I.e. pure refactoring changes should not be in one PR with changes that relate to performance improvements. Thanks!

**Comment by novichkovg** [comment]
> c

I definitely plan to do any refactoring **after** I finish the task. Refactoring can break things, so it'd be better to have something working first.

**Comment by novichkovg** [comment]
Functionality implemented, added test coverage.  @Garra1980 , @ienkovich please check.
