### ISSUE TITLE
Add builds to Github Actions

### ISSUE THREAD

**Issue by alexbaden** [intel-ai/omniscidb#331]
- [x] CPU Only Build
- [x] CUDA Build
- [x] DBE On Build (w/ CUDA?)

**Comment by leshikus** [comment]
Current status:
1) documentation is generated, see https://intel-ai.github.io/omniscidb/
2) the build works in github runner, tests kill the runner somehow,
3) the build fails in self-hosted runner, looking into it

**Comment by alexbaden** [comment]
The documentation is setup to bring in doxygen inline with the Sphinx-generated markdown. This process takes a long time and was difficult to get right. I am not sure it is worth keeping -- if that's part of the problem, we should consider separating the sphinx and doxygen components like many other open source projects.

**Comment by leshikus** [comment]
@alexbaden As for documentation, I've fixed the "upload to gh pages" part.

Please check if "result_packages" from https://github.com/intel-ai/omniscidb/actions/runs/2063948498 look like the build you expect.

What is "DBE On Build"?

**Comment by Garra1980** [comment]
> What is "DBE On Build"?

build with DBE enabled, see https://github.com/intel-ai/omniscidb/blob/modin/scripts/conda/build.sh#L82

**Comment by Garra1980** [comment]
I'd say this should be our default build mode for CPU at least

**Comment by alexbaden** [comment]
The packages look right but it doesn't quite work:
```
/tmp/result_packages » ./bin/omnisci_server --version         
./bin/omnisci_server: error while loading shared libraries: libarrow.so.500: cannot open shared object file: No such file or directory
```
We likely need to build with `-DPREFER_STATIC_LIBS=on`. This may require some custom builds of some of the dependencies.

**Comment by Garra1980** [comment]
> The packages look right but it doesn't quite work:
> 
> ```
> /tmp/result_packages » ./bin/omnisci_server --version         
> ./bin/omnisci_server: error while loading shared libraries: libarrow.so.500: cannot open shared object file: No such file or directory
> ```
> 
> We likely need to build with `-DPREFER_STATIC_LIBS=on`. This may require some custom builds of some of the dependencies.

Or is it just wrong deps used?

**Comment by alexbaden** [comment]
Depends on whether we want to require matching deps installation on users machine or deploy a single, statically linked binary. I suppose with Conda the former is ok?

**Comment by Garra1980** [comment]
> Depends on whether we want to require matching deps installation on users machine or deploy a single, statically linked binary. 

Right

>I suppose with Conda the former is ok?

Yes, should be ok

**Comment by leshikus** [comment]
>> -DPREFER_STATIC_LIBS=on
to change to the static build all libs have to be recompiled statically, e.g. arrow
inventing "static conda" is technically possible, i've tried that for boost-cpp; yet imho this is out of the scope of the original CI task

**Comment by ienkovich** [comment]
> I'd say this should be our default build mode for CPU at least

We decided that using DBE doesn't follow the modular approach of HDK. So rather than modifying the current embedded library, we will completely drop it from `jit-branch` soon and later will introduce a more granular Python API which would provide access to different HDK components from Python. HDK backend in Modin will be built on top of those new APIs. So, for the `jit-engine` branch DBE will not be enabled in CI.

**Comment by Garra1980** [comment]
> > I'd say this should be our default build mode for CPU at least
> 
> We decided that using DBE doesn't follow the modular approach of HDK. So rather than modifying the current embedded library, we will completely drop it from `jit-engine` soon and later will introduce a more granular Python API which would provide access to different HDK components from Python. HDK backend in Modin will be built on top of those new APIs. So, for the `jit-engine` branch DBE will not be enabled in CI.


Of course DBE will be changed, I meant for now, why we can't do it? Once DBE dropped CI will be changed accordingly

**Comment by ienkovich** [comment]
> Of course DBE will be changed, I meant for now, why we can't do it? Once DBE dropped CI will be changed accordingly

If it doesn't require any significant effort, then sure. But I'm going to remove DBE from `jit-engine` branch next week.

**Comment by leshikus** [comment]
I appreciate help with fixing / disabling failed tests. https://github.com/intel-ai/omniscidb/runs/5784131734

**Comment by leshikus** [comment]
It seems some tests use incorrect place for logging (/mapd_log//log4j.log)

**Comment by leshikus** [comment]
This request enables cuda build https://github.com/intel-ai/omniscidb/pull/352/

**Comment by alexbaden** [comment]
Resolved. We now have builds + unit tests running in Github Actions.
