### ISSUE TITLE
Select.FilterAndSimpleAggregation fails on CPU when CUDA is enabled

### ISSUE THREAD

**Issue by kurapov-peter** [intel-ai/omniscidb#362]
```
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from Select
[ RUN      ] Select.FilterAndSimpleAggregation
Tests/SQLiteComparator.cpp:96: Failure
Expected equality of these values:
  ref_val
    Which is: 15
  omnisci_val
    Which is: 0
CPU: SELECT COUNT(*) FROM test WHERE o1 > '1999-09-08';
Tests/SQLiteComparator.cpp:96: Failure
Expected equality of these values:
  ref_val
    Which is: 0
  omnisci_val
    Which is: 15
CPU: SELECT COUNT(*) FROM test WHERE o1 <= '1999-09-08';
2022-04-16T23:19:51.852455 F 149613 0 0 ArrowStorage.cpp:122 Check failed: elems > 0 (0 > 0) 
Aborted (core dumped)
```

**Comment by kurapov-peter** [comment]
Seems like a date problem, fails on:
```c("SELECT COUNT(*) FROM test WHERE o1 > '1999-09-08';", dt);```

**Comment by kurapov-peter** [comment]
Reproducible without latest changes, ie. at 9f137c376b9222fe46f5b5e85a5b219984e5d165

**Comment by kurapov-peter** [comment]
The code generated in both cases is identical.
Changing date size for `o, o1, o2` changes the output values:
```
Expected equality of these values:
  ref_val
    Which is: 15
  omnisci_val
    Which is: 7
CPU: SELECT COUNT(*) FROM test WHERE o1 > '1999-09-08';
Expected equality of these values:
  ref_val
    Which is: 0
  omnisci_val
    Which is: 2
```

2022-04-16T23:19:51.852455 F 149613 0 0 ArrowStorage.cpp:122 Check failed: elems > 0 (0 > 0) --- happens due to `elem_size` being less than `arrow_elem_size` in https://github.com/intel-ai/omniscidb/blob/jit-engine/ArrowStorage/ArrowStorage.cpp#L126
A rounding division fixes the issue although the logic seem incorrect to me.

**Comment by ienkovich** [comment]
In this part of code `elem_size` shouldn't be less than `arrow_elem_size`. `elem_size` should be either the same (in case of a scalar type) or divisible by `arrow_elem_size` (fixed-size array case). How does CUDA enabling affect type sizes?

**Comment by kurapov-peter** [comment]
Ugh... I spent several hours debugging the thing just to discover this: https://github.com/intel-ai/omniscidb/blob/jit-engine/ArrowStorage/ArrowStorageUtils.cpp#L969 

Where does the gpu dates storage size restriction come from?

**Comment by ienkovich** [comment]
This comes from legacy FSI code. I don't know what it is here for.

**Comment by ienkovich** [comment]
[Here ](https://github.com/intel-ai/omniscidb/blob/jit-engine/ArrowStorage/ArrowStorageUtils.cpp#L1026) we always expect Arrow type to use 4-byte values for dates. I'd try to remove forcing 8-byte Arrow type for dates when CUDA is enabled.
