### ISSUE TITLE
Add taxi benchmark to github actions CPU CI

### ISSUE THREAD

**Issue by alexbaden** [intel-ai/omniscidb#410]
We have scripts which populate data and run queries using the google benchmark framework checked into the repo: https://github.com/intel-ai/omniscidb/blob/jit-engine/Benchmarks/taxi/taxi_reduced_bench.cpp

We should run these nightly as part of our CI. Google benchmark can output in various formats which should be readable by grafana or some other monitoring tool. We could also just output the raw values and visually check between different runs. 

Google benchmark also has a compare tool which we might leverage to make runs report status automatically: https://github.com/google/benchmark/blob/main/docs/tools.md (see bottom section on U test).

**Comment by leshikus** [comment]
I've successfully compiled build/bin/taxi_reduced

I believe to get it working I need to specify something in --data option. What is the correct dataset to run?

**Comment by Garra1980** [comment]
this is a good question - we have prepared dataset on which we can try CI runs but it weights 170M. Is it something we can deal with?
Another option is to generate reduced dataset eg using generator from here - https://github.com/gshimansky/data-science-processing-workload/blob/master/generator/generator.py

**Comment by leshikus** [comment]
Let me try 170 M. I just need the file names / locations to try.

**Comment by leshikus** [comment]
I've implemented the base variant. Should I 1) run the benchmark several times to get an average; 2) build a graph with several last benchmark values?

**Comment by Garra1980** [comment]
I think we can try 3 times and pick median

**Comment by Garra1980** [comment]
@leshikus are we done here?

**Comment by leshikus** [comment]
No, a pull request awaits a review https://github.com/intel-ai/omniscidb/pull/431

**Comment by Garra1980** [comment]
Right! thanks for noting
