### ISSUE TITLE
UdfTest does not work for CUDA

### ISSUE THREAD

**Issue by leshikus** [intel-ai/omniscidb#489]
```
unknown file: Failure
C++ exception with description "std::bad_alloc" thrown in auxiliary test code (environments or event listeners).
```

The error is produced in the line
```
UdfCompiler compiler(g_device_arch, std::string(""), udf_compiler_options);
```

I've noticed that `UdfCompiler` constructor in `UdfCompiler.cpp` was not called, maybe because it has a different number of arguments for CUDA. This may be a result of a fallback to a default constructor. Or some clang lib may be missed.

I have CPLUS_INCLUDE_PATH set and exported, this seem not be an issue
```
# set | grep PLUS
CPLUS_INCLUDE_PATH=/usr/include/c++/9:/usr/include/x86_64-linux-gnu/c++/9:/usr/include/c++/9/backward:/usr/lib/gcc/x86_64-linux-gnu/9/include:/usr/local/include:/usr/include/x86_64-linux-gnu:/usr/include
```

Please help me to resolve this, this blocks enabling tests for CI.

The problem can be reproduced using the following container:
```
docker exec -ti build.cuda bash
cd /omniscidb/build/Tests/
make && ./UdfTest
```

**Comment by Garra1980** [comment]
probably we can skip this particular test for now

**Comment by leshikus** [comment]
@ienkovich what do you think of excluding UdfTest? I've prepared the patch https://github.com/intel-ai/omniscidb/actions/runs/3022951920

**Comment by leshikus** [comment]
>> because it has a different number of arguments
this was not correct

**Comment by leshikus** [comment]
>> clang_path_(get_clang_path(clang_path_override))
error comes from here

**Comment by leshikus** [comment]
This helped, export PATH=/usr/lib/llvm-12/bin:$PATH
