### ISSUE TITLE
Latest jdk version causes tests failure in conda envs

### ISSUE THREAD

**Issue by kurapov-peter** [intel-ai/omniscidb#502]
Breaks our CI, example: https://github.com/intel-ai/omniscidb/actions/runs/3114356526/jobs/5050439385

**Comment by Garra1980** [comment]
I don't like https://github.com/intel-ai/omniscidb/actions/runs/3114356526/jobs/5050439385#step:9:13 in the first place

**Comment by Garra1980** [comment]
My impression that jdk is not a reason since we have
https://github.com/intel-ai/omniscidb/actions/runs/3108819862/jobs/5038430680#step:6:472

**Comment by kurapov-peter** [comment]
This was just Alexei's guess, not sure of the root cause now. Clearly some pathing issue.

**Comment by Garra1980** [comment]
Yesterday CI was ok, I'd say there is an issue with lack of disk space or smth like that

**Comment by leshikus** [comment]
Works for me https://github.com/intel-ai/omniscidb/actions/runs/3117682041

Though there is some other problem in docker

**Comment by Garra1980** [comment]
This one is for conda env build

**Comment by Garra1980** [comment]
And there is still 

bash scripts/conda/test.sh
ERROR conda.cli.main_run:execute(41): `conda run bash scripts/conda/test.sh` failed. (See above for error)

**Comment by kurapov-peter** [comment]
Looks like the `cplus_include_path` is incorrectly set as it doesn't contain any conda paths.

**Comment by Garra1980** [comment]
Doesn’t explain why it works for Alexei though

**Comment by kurapov-peter** [comment]
I see Alexei's example uses a different set of rules, testing it here https://github.com/intel-ai/omniscidb/actions/runs/3119677269

**Comment by kurapov-peter** [comment]
I think, it stopped working...

**Comment by kurapov-peter** [comment]
Although some actions seem to run correctly, there's one here that failed suspiciously: https://github.com/intel-ai/omniscidb/actions/runs/3129926216/jobs/5079964858

**Comment by Garra1980** [comment]
@leshikus please take a look

**Comment by leshikus** [comment]
Ok, may I restore the variant with caches? I add invalidating them after the failed build, thus this should fix the issue like this.

**Comment by Garra1980** [comment]
Can we maybe run everything from scratch each time to avoid incompatibility issues?

**Comment by leshikus** [comment]
It means I download and install 1 Gb of packages for each of 3 containers and 4 Gb of packages for build-cuda for each run. Also this may lead to a case when the test environment is newer than the build environment.

Do we accept all associated risks and costs?

**Comment by kurapov-peter** [comment]
> Ok, may I restore the variant with caches? I add invalidating them after the failed build, thus this should fix the issue like this.

This sounds fine, running everything from scratch would be too much I think.

**Comment by leshikus** [comment]
Another 1Gb is downloaded for clang-test

I've made a partial fix for the issue, probably it will be good enough
